apiVersion: v1
kind: Service
metadata:
  name: static-service
  namespace: default
spec:
  selector:
    app:  static-website
  type: ClusterIP
  ports:
  - name: static-website
    protocol: TCP
    port: 80
    targetPort: 80
