apiVersion: v1
kind: Service
metadata:
  name: static-service
  namespace: default
spec:
  selector:
    app: static-app
  type: ClusterIP
  ports:
  - name: static-service
    protocol: TCP
    port: 80
    targetPort: 80
